---
deployment:
  tasks:
    - export DEPLOYPATH=/home/edictosyavisosno/public_html/dev.diarionacional.com.mx/a/wp-content/themes/diario-nacional-theme/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
